"""Daily encrypted database backup to Cloudflare R2, driven by the dispatcher.

Supabase's free tier has no automated backups and no point-in-time recovery, so without this a bad
migration or a lost project is unrecoverable.

Why it lives in the dispatcher rather than its own cron: Render's cron jobs need a paid plan, and the
`run-dispatcher` job already fires every 5 minutes from Supabase pg_cron. This self-gates to once a
day through job_run_history, the same way reconcile_payments does, so it costs one cheap check per
tick and needs no new infrastructure.

Deliberately uses NO external binaries. pg_dump and gpg may or may not exist in Render's image, and a
backup that fails at 2am on a service nobody is watching is worse than none. Everything here runs on
psycopg and cryptography, both already dependencies.

The dump is plain SQL INSERTs, encrypted with Fernet (AES-128-CBC + HMAC) before it leaves this
process. Encryption is not optional: the database holds customer emails, phone numbers and payment
records, and R2 is a third party.

Required env (on the Render web service, since that is what the dispatcher hits):
  R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET
  BACKUP_KEY   a Fernet key. LOSE IT AND EVERY BACKUP IS UNREADABLE.
               generate: python -c "from cryptography.fernet import Fernet;print(Fernet.generate_key().decode())"

Restore:
  python -m scripts.restore_backup immigroov-2026-08-16.sql.gz.enc
"""
from __future__ import annotations

import gzip
import logging
import os
from datetime import datetime, timedelta, timezone

import psycopg
from cryptography.fernet import Fernet
from psycopg.types.json import Jsonb

import config

logger = logging.getLogger("immigroov.backup")

JOB_NAME = "backup_to_r2"
INTERVAL = timedelta(hours=23)          # once a day, with slack so a late tick still qualifies
RETENTION_DAYS = int(os.getenv("BACKUP_RETENTION_DAYS", "30"))

# Skipped: regenerated by setup, or reconstructable, or huge and worthless in a backup.
SKIP_TABLES = {
    "checkpoints", "checkpoint_blobs", "checkpoint_writes", "checkpoint_migrations",
    "ai_events", "webhook_events", "dispatcher_locks", "job_run_history",
}


def _dump_sql(dsn: str) -> bytes:
    """Whole database as INSERT statements. ClientCursor renders parameters into literal SQL, which
    is what makes this safe for arrays, jsonb and timestamptz; hand-rolled quoting would not be."""
    out: list[str] = [
        "-- Immigroov database backup",
        f"-- taken: {datetime.now(timezone.utc).isoformat()}",
        "",
        "BEGIN;",
        "",
    ]
    with psycopg.connect(dsn) as conn:
        cur = psycopg.ClientCursor(conn)
        cur.execute("""select table_name from information_schema.tables
                       where table_schema='public' and table_type='BASE TABLE' order by table_name""")
        tables = [r[0] for r in cur.fetchall() if r[0] not in SKIP_TABLES]
        for t in tables:
            cur.execute("""select column_name, data_type from information_schema.columns
                           where table_schema='public' and table_name=%s order by ordinal_position""", (t,))
            cols_types = cur.fetchall()
            cols = [c for c, _ in cols_types]
            jsonb = {c for c, dt in cols_types if dt in ("json", "jsonb")}
            collist = ", ".join(f'"{c}"' for c in cols)
            cur.execute(f'select {collist} from "{t}"')
            rows = cur.fetchall()
            if not rows:
                continue
            out.append(f"-- {t}: {len(rows)} rows")
            ph = ", ".join(["%s"] * len(cols))
            for row in rows:
                vals = [Jsonb(v) if (c in jsonb and v is not None) else v for c, v in zip(cols, row)]
                out.append(cur.mogrify(
                    f'INSERT INTO "{t}" ({collist}) VALUES ({ph}) ON CONFLICT DO NOTHING;', vals))
            out.append("")
    out.append("COMMIT;")
    return "\n".join(out).encode("utf-8")


def run_backup(force: bool = False) -> dict:
    """Dispatcher entry point. Self-gates to once a day."""
    from db import jobs as job_db

    if not force and not job_db.job_is_due(JOB_NAME, INTERVAL):
        return {"skipped": "backed up within the last 23h"}

    missing = [k for k in ("R2_ACCOUNT_ID", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY",
                           "R2_BUCKET", "BACKUP_KEY") if not os.getenv(k)]
    if missing:
        return {"skipped": f"not configured: {', '.join(missing)}"}

    try:
        import boto3
    except ImportError:
        return {"error": "boto3 not installed"}

    dsn = config.SUPABASE_DB_URL
    if not dsn:
        return {"error": "no database URL"}

    raw = _dump_sql(dsn)
    packed = gzip.compress(raw, compresslevel=9)
    blob = Fernet(os.environ["BACKUP_KEY"].encode()).encrypt(packed)

    key = f"immigroov-{datetime.now(timezone.utc):%Y-%m-%d}.sql.gz.enc"
    s3 = boto3.client(
        "s3",
        endpoint_url=f"https://{os.environ['R2_ACCOUNT_ID']}.r2.cloudflarestorage.com",
        aws_access_key_id=os.environ["R2_ACCESS_KEY_ID"],
        aws_secret_access_key=os.environ["R2_SECRET_ACCESS_KEY"],
        region_name="auto",
    )
    s3.put_object(Bucket=os.environ["R2_BUCKET"], Key=key, Body=blob)

    # Prune only AFTER a successful upload, so a failed run can never leave fewer backups than it
    # started with.
    cutoff = datetime.now(timezone.utc) - timedelta(days=RETENTION_DAYS)
    pruned = 0
    try:
        for page in s3.get_paginator("list_objects_v2").paginate(Bucket=os.environ["R2_BUCKET"]):
            for obj in page.get("Contents", []):
                if obj["Key"] != key and obj["LastModified"] < cutoff:
                    s3.delete_object(Bucket=os.environ["R2_BUCKET"], Key=obj["Key"])
                    pruned += 1
    except Exception:
        logger.exception("backup uploaded but pruning failed")

    job_db.mark_job_run(JOB_NAME)
    return {"ok": True, "key": key, "raw_kb": round(len(raw) / 1024, 1),
            "stored_kb": round(len(blob) / 1024, 1), "pruned": pruned}
