#!/usr/bin/env python3
"""Dump staging's mentor data as a plain .sql file to paste into the production SQL editor.

Why this instead of re-running the legacy-API migration on prod: staging's data has ALREADY been
through every corrective pass (base currencies realigned to each mentor's own sessions, prices
reimported, expertise countries fixed, categories remapped). Re-importing from the legacy API on prod
would reproduce the raw data and then need the same chain of fixes re-run and re-verified there. This
copies the finished result instead, so prod cannot end up in a state staging never had.

What comes across: the 67 migrated mentors and their services, questions, availability, cancellation
policy and legacy session history.

What deliberately does NOT:
  * mentors created via staging signup (no legacy_id) - the three test accounts
  * every transactional table - bookings, payments, payouts, ledgers, quotes, reviews. Those carry
    Razorpay TEST-mode ids that do not exist in live mode and would corrupt the payout ledger.
  * mentor_bank_accounts - encrypted under staging's BANK_ENC_KEY, unreadable with prod's. Mentors
    re-enter payout details on prod.
  * profile_id is NULLed. It points at a staging auth user who does not exist in prod; each mentor
    re-links by email on their first prod login.

Reference tables (platform_settings, ppp_factors, country_pricing, fx_rates) are NOT included: the
schema script seeds them and the dispatcher refreshes FX on prod already.

Usage:
    python -m scripts.export_prod_seed                 # -> scripts/prod_seed.sql
    python -m scripts.export_prod_seed --out other.sql

Then paste the file into the prod SQL editor and run. Every statement is ON CONFLICT DO NOTHING, so
re-running is safe.
"""
from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path

import psycopg
from psycopg.types.json import Jsonb

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger("export")

# Parent first: services before service_questions, mentors before everything.
TABLES: list[tuple[str, str]] = [
    ("mentors",                   "WHERE legacy_id IS NOT NULL"),
    ("services",                  "WHERE mentor_id IN (SELECT id FROM mentors WHERE legacy_id IS NOT NULL)"),
    ("service_questions",         "WHERE service_id IN (SELECT id FROM services WHERE mentor_id IN (SELECT id FROM mentors WHERE legacy_id IS NOT NULL))"),
    ("weekly_availability",       "WHERE mentor_id IN (SELECT id FROM mentors WHERE legacy_id IS NOT NULL)"),
    ("specific_availability",     "WHERE mentor_id IN (SELECT id FROM mentors WHERE legacy_id IS NOT NULL)"),
    ("mentor_availability",       "WHERE mentor_id IN (SELECT id FROM mentors WHERE legacy_id IS NOT NULL)"),
    ("mentor_cancellation_policy","WHERE mentor_id IN (SELECT id FROM mentors WHERE legacy_id IS NOT NULL)"),
    ("legacy_sessions",           "WHERE mentor_id IN (SELECT id FROM mentors WHERE legacy_id IS NOT NULL)"),
]

# Columns blanked on the way out, whatever their value in staging.
NULLED = {"mentors": ["profile_id"]}


def jsonb_columns(cur, table: str) -> set[str]:
    cur.execute("""SELECT column_name FROM information_schema.columns
                   WHERE table_schema='public' AND table_name=%s AND data_type IN ('json','jsonb')""",
                (table,))
    return {r[0] for r in cur.fetchall()}


def export(dsn: str, out: Path) -> int:
    lines: list[str] = [
        "-- Groovia production seed: migrated mentors and their data, exported from staging.",
        "-- Generated by scripts/export_prod_seed.py. Safe to re-run (ON CONFLICT DO NOTHING).",
        "--",
        "-- Excludes: signup-created test mentors, ALL transactional data (bookings, payments,",
        "-- payouts, ledgers, quotes, reviews) and mentor_bank_accounts. profile_id is NULL so each",
        "-- mentor re-links to their prod auth account by email on first login.",
        "",
        "BEGIN;",
        "",
    ]
    total = 0
    with psycopg.connect(dsn) as conn:
        # ClientCursor does parameter adaptation client-side, which is what lets us render a literal
        # SQL string instead of sending it. Hand-rolling the quoting here would be a bug factory:
        # arrays, jsonb, timestamptz and embedded quotes all need different handling.
        cur = psycopg.ClientCursor(conn)
        for table, where in TABLES:
            jsonb = jsonb_columns(cur, table)
            cur.execute(f"""SELECT column_name FROM information_schema.columns
                            WHERE table_schema='public' AND table_name='{table}'
                            ORDER BY ordinal_position""")
            cols = [r[0] for r in cur.fetchall()]
            if not cols:
                log.warning("   %-28s table not found, skipped", table)
                continue

            cur.execute(f"SELECT {', '.join(cols)} FROM {table} {where}")
            rows = cur.fetchall()
            log.info("   %-28s %4d rows", table, len(rows))
            if not rows:
                continue
            total += len(rows)

            collist = ", ".join(cols)
            lines.append(f"-- {table}: {len(rows)} rows")
            for row in rows:
                vals = []
                for col, v in zip(cols, row):
                    if col in NULLED.get(table, []):
                        v = None
                    vals.append(Jsonb(v) if (col in jsonb and v is not None) else v)
                stmt = cur.mogrify(
                    f"INSERT INTO {table} ({collist}) VALUES ({', '.join(['%s'] * len(cols))}) "
                    f"ON CONFLICT DO NOTHING;", vals)
                lines.append(stmt)
            lines.append("")

    lines += ["COMMIT;", "",
              "-- Verify:",
              "--   SELECT COUNT(*) FROM mentors;                        -- expect the migrated count",
              "--   SELECT COUNT(*) FROM mentors WHERE legacy_id IS NULL; -- expect 0",
              "--   SELECT COUNT(*) FROM bookings;                        -- expect 0",
              "--   SELECT COUNT(*) FROM mentors WHERE profile_id IS NOT NULL; -- expect 0 before logins",
              ""]

    out.write_text("\n".join(lines), encoding="utf-8")
    log.info("\n%d rows -> %s (%.1f KB)", total, out, out.stat().st_size / 1024)
    log.info("Paste it into the production SQL editor and run.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default="scripts/prod_seed.sql", help="output .sql path")
    args = ap.parse_args()

    from dotenv import load_dotenv
    load_dotenv(".env.staging")
    dsn = os.getenv("DATABASE_URL") or os.getenv("SUPABASE_DB_URL")
    if not dsn:
        log.error("DATABASE_URL not set (expected in .env.staging)")
        return 1
    return export(dsn, Path(args.out))


if __name__ == "__main__":
    raise SystemExit(main())
